# Joint Summer Faculty Development Program 2020

##Machine Learning for Computer Vision
##June 29 to July 8, 2020

**Principal Coordinator - IIITDM Jabalpur : Co-Principal Coordinator - MNIT Jaipur**

**Particiapting Academies -** IIT Guwahati, MNIT Jaipur, NIT Patna, IIITDM Jabalpur 

# Assignment 1: Introduction to Python  

---



**Exercise 1.** Create following list:

data = [2,34,23,16,56,45,34,26,78,56,1,16]

Now delete the duplicate values and print the list in ascending order. 

In [2]:
data = [2,34,23,16,56,45,34,26,78,56,1,16]
data = list( dict.fromkeys(data) )
data = sorted(data)
print(data)

[1, 2, 16, 23, 26, 34, 45, 56, 78]


**Exercise 2:** Take five numbers as input from the user and save into a list. Find the maximum of the list and sort the data in descending order.

In [49]:
int_value = [int(x) for x in input("Enter three value: ").split(',')] 
print(int_value)
print("The maximum value of list is:- ",max(int_value))
print("The sort in descending order is :-",sorted(int_value , reverse = True))

Enter three value: 1,2,3,4,5
[1, 2, 3, 4, 5]
The maximum value of list is:-  5
The sort in descending order is :- [5, 4, 3, 2, 1]


**Exercise 4:**

(i) Generate two arrays A1 and A2 of size 5 X 4 and 3 X 4 respectively using np.random()

(ii) Join them and make an array A3 of 8 X 4. Now append random numbers ranging between from 0 to 5 to make the fourth array A4 of size 10 X 10. 

(iii) Print all the arrays and their transpose ( Transpose of 'A' can be obtained by 'A.T') 

In [76]:
import numpy as np 
from numpy import random
A1 = np.random.rand(5,4)
A2 = np.random.rand(3,4)   
A3 = np.concatenate((A1,A2))
A4 = np.random.randint(0,5,(10,10))
print("The Matrix A1 is :-\n\n ", A1)
print("The Transpose of A1 is :-\n\n ",np.transpose(A1))

print("The Matrix A2 is :-\n\n ", A2)
print("The Transpose of A2 is :-\n\n ",np.transpose(A2))

print("The Matrix A3 is :-\n\n ", A3)
print("The Transpose of A3 is :-\n\n ",np.transpose(A3))

print("The Matrix A4 is :-\n\n ", A4)
print("The Transpose of A4 is :-\n\n ",np.transpose(A4))

print("The shape of  A1 is :-\n ", A1.shape)
print("The shape of  A2 is :-\n ", A2.shape)
print("The shape of  A3 is :-\n ", A3.shape)
print("The shape of  A4 is :-\n ", A4.shape)

The Matrix A1 is :-

  [[0.02588295 0.22201816 0.06888415 0.13820617]
 [0.24977303 0.30625047 0.26022646 0.23071607]
 [0.08763079 0.49326965 0.2971213  0.16224529]
 [0.96284128 0.17143369 0.04346081 0.47547376]
 [0.33081979 0.92700861 0.59226621 0.92458914]]
The Transpose of A1 is :-

  [[0.02588295 0.24977303 0.08763079 0.96284128 0.33081979]
 [0.22201816 0.30625047 0.49326965 0.17143369 0.92700861]
 [0.06888415 0.26022646 0.2971213  0.04346081 0.59226621]
 [0.13820617 0.23071607 0.16224529 0.47547376 0.92458914]]
The Matrix A2 is :-

  [[0.72484513 0.45379047 0.83933961 0.13061817]
 [0.57794856 0.16268999 0.55386758 0.30362734]
 [0.90462473 0.48744361 0.52728492 0.03581469]]
The Transpose of A2 is :-

  [[0.72484513 0.57794856 0.90462473]
 [0.45379047 0.16268999 0.48744361]
 [0.83933961 0.55386758 0.52728492]
 [0.13061817 0.30362734 0.03581469]]
The Matrix A3 is :-

  [[0.02588295 0.22201816 0.06888415 0.13820617]
 [0.24977303 0.30625047 0.26022646 0.23071607]
 [0.08763079 0.49326965

**Exercise 5: Create two dictionaries.** 

The first dictionary 'name' will contain first name(key) of a person and its hash value(value). 
The Second will contain hash value(key) and mobile no(value). 


i) Add 5 entries.

ii) Delete two entries by taking the input from user as the first name.

ii) Add two entries by taking the input as the first name and mobile no. 

Hint: You can use remainder ( %) to obtain hash value. 

In [4]:
# Not able to answer

E&ICT PDPM IIITDM Jabalpur